// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student.Data;

#nullable disable

namespace student.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240723093408_TbWard")]
    partial class TbWard
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"));

                    b.Property<int?>("IdNation")
                        .HasColumnType("int");

                    b.Property<string>("NameCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCity");

                    b.HasIndex("IdNation");

                    b.ToTable("City");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.Property<int>("IdDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistrict"));

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("NameDistrict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDistrict");

                    b.HasIndex("IdCity");

                    b.ToTable("District");
                });

            modelBuilder.Entity("student.Data.Nation", b =>
                {
                    b.Property<int>("IdNation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNation"));

                    b.Property<string>("NameNation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleNation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNation");

                    b.ToTable("Nation");
                });

            modelBuilder.Entity("student.Data.Ward", b =>
                {
                    b.Property<int>("IdWard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWard"));

                    b.Property<int?>("IdDistrict")
                        .HasColumnType("int");

                    b.Property<string>("NameWard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleWard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdWard");

                    b.HasIndex("IdDistrict");

                    b.ToTable("Ward");
                });

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.HasOne("student.Data.Nation", "Nation")
                        .WithMany("Citys")
                        .HasForeignKey("IdNation");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.HasOne("student.Data.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("IdCity");

                    b.Navigation("City");
                });

            modelBuilder.Entity("student.Data.Ward", b =>
                {
                    b.HasOne("student.Data.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("IdDistrict");

                    b.Navigation("District");
                });

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.Navigation("Wards");
                });

            modelBuilder.Entity("student.Data.Nation", b =>
                {
                    b.Navigation("Citys");
                });
#pragma warning restore 612, 618
        }
    }
}
