// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using student.Data;

#nullable disable

namespace student.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240724020919_TbStudent")]
    partial class TbStudent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"));

                    b.Property<int?>("IdNation")
                        .HasColumnType("int");

                    b.Property<string>("NameCity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCity");

                    b.HasIndex("IdNation");

                    b.ToTable("City");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.Property<int>("IdDistrict")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistrict"));

                    b.Property<int?>("IdCity")
                        .HasColumnType("int");

                    b.Property<string>("NameDistrict")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleDistrict")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdDistrict");

                    b.HasIndex("IdCity");

                    b.ToTable("District");
                });

            modelBuilder.Entity("student.Data.Nation", b =>
                {
                    b.Property<int>("IdNation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNation"));

                    b.Property<string>("NameNation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleNation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNation");

                    b.ToTable("Nation");
                });

            modelBuilder.Entity("student.Data.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"));

                    b.Property<DateTime?>("BirthDayStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdCity")
                        .HasColumnType("int");

                    b.Property<int>("IdDistrict")
                        .HasColumnType("int");

                    b.Property<int>("IdNation")
                        .HasColumnType("int");

                    b.Property<int>("IdWard")
                        .HasColumnType("int");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdCity");

                    b.HasIndex("IdDistrict");

                    b.HasIndex("IdNation");

                    b.HasIndex("IdWard");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("student.Data.Ward", b =>
                {
                    b.Property<int>("IdWard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdWard"));

                    b.Property<int?>("IdDistrict")
                        .HasColumnType("int");

                    b.Property<string>("NameWard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleWard")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdWard");

                    b.HasIndex("IdDistrict");

                    b.ToTable("Ward");
                });

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.HasOne("student.Data.Nation", "Nation")
                        .WithMany("Citys")
                        .HasForeignKey("IdNation");

                    b.Navigation("Nation");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.HasOne("student.Data.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("IdCity");

                    b.Navigation("City");
                });

            modelBuilder.Entity("student.Data.Student", b =>
                {
                    b.HasOne("student.Data.City", "City")
                        .WithMany("Students")
                        .HasForeignKey("IdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("student.Data.District", "District")
                        .WithMany("Students")
                        .HasForeignKey("IdDistrict")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("student.Data.Nation", "Nation")
                        .WithMany("Students")
                        .HasForeignKey("IdNation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("student.Data.Ward", "Ward")
                        .WithMany("Students")
                        .HasForeignKey("IdWard")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");

                    b.Navigation("Nation");

                    b.Navigation("Ward");
                });

            modelBuilder.Entity("student.Data.Ward", b =>
                {
                    b.HasOne("student.Data.District", "District")
                        .WithMany("Wards")
                        .HasForeignKey("IdDistrict");

                    b.Navigation("District");
                });

            modelBuilder.Entity("student.Data.City", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("student.Data.District", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Wards");
                });

            modelBuilder.Entity("student.Data.Nation", b =>
                {
                    b.Navigation("Citys");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("student.Data.Ward", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
